# load .Xresources configuration
xrdb -merge .Xresources

# set the background image (requires graphics/feh)
feh --bg-fill /home/bsdboy/Pictures/wallpapers/arch-linux.jpg &

# I use x11/rxvt-unicode for my terminal emulator - you can run a server
# process to conserve resources.
urxvtd -q -f -o

# install sysutils/dunst for lightweight OSD notifications
dunst &

# start your window manager here
exec i3
